services:
  flask_api:
    build: ./python-api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - "./python-api:/app"
    command: "python app.py"
    depends_on:
      - mysql_db
    networks:
      - app-networks

  node_api:
    build: ./node-api
    container_name: node_api
    ports:
      - "3000:3000"
    volumes:
      - "./node-api:/app"
    command: "npm start"
    depends_on:
      - flask_api
    networks:
      - app-networks

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
